<a href="https://colab.research.google.com/github/Shreeyamshu/Ai/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Array Creation

import numpy as np

# 1 Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty array (2x2):")
print(empty_array)

# 2 Initialize an all one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All ones array (4x2):")
print(ones_array)

# 3 Return new array filled with fill_value
filled_array = np.full((3, 3), 7)  # 3x3 array filled with 7
print("\n3. Array filled with value 7:")
print(filled_array)

# 4 Return zeros with same shape and type as given array
sample_array = np.array([[1, 2], [3, 4]], dtype=float)
zeros_like_array = np.zeros_like(sample_array)
print("\n4. Zeros like sample array:")
print(zeros_like_array)

# 5 Return ones with same shape and type as given array
ones_like_array = np.ones_like(sample_array)
print("\n5. Ones like sample array:")
print(ones_like_array)

# 6 Convert list to numpy array
new_list = [1, 2, 3, 4]
list_to_array = np.array(new_list)
print("\n6. List converted to array:")
print(list_to_array)

1. Empty array (2x2):
[[5.16731554e-315 0.00000000e+000]
 [1.25990592e-300 1.39067116e-309]]

2. All ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like sample array:
[[0. 0.]
 [0. 0.]]

5. Ones like sample array:
[[1. 1.]
 [1. 1.]]

6. List converted to array:
[1 2 3 4]


In [2]:
#Array Manipulation: Numerical Ranges and Array indexing

import numpy as np

# 1 Array with values from 10 to 49
arr_10_49 = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr_10_49)

# 2 3x3 matrix with values 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0-8):")
print(matrix_3x3)

# 3 3x3 identity matrix
identity_3x3 = np.eye(3)
print("\n3. 3x3 identity matrix:")
print(identity_3x3)

# 4 Random array of size 30 and mean
random_arr = np.random.random(30)
random_mean = random_arr.mean()
print(f"\n4. Random array mean: {random_mean:.4f}")

# 5 10x10 random array with min/max
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print(f"5. 10x10 array - Min: {min_val:.4f}, Max: {max_val:.4f}")

# 6 Zero array with 5th element replaced
zero_arr = np.zeros(10)
zero_arr[4] = 1  # 5th element (index 4)
print("\n6. Zero array with 5th element as 1:")
print(zero_arr)

# 7 Reverse array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:")
print(reversed_arr)

# 8 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. Border array (1 on border, 0 inside):")
print(border_array)

# 9 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows, odd columns
print("\n9. 8x8 Checkerboard pattern:")
print(checkerboard)

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0-8):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array mean: 0.5194
5. 10x10 array - Min: 0.0087, Max: 0.9979

6. Zero array with 5th element as 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
[0 4 0 0 2 1]

8. Border array (1 on border, 0 inside):
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
# Array Operations:

import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Original arrays:")
print(f"x = \n{x}")
print(f"y = \n{y}")
print(f"v = {v}")
print(f"w = {w}")

# 1 Add the two arrays
add_xy = x + y
print("\n1. x + y:")
print(add_xy)

# 2 Subtract the two arrays
sub_xy = x - y
print("\n2. x - y:")
print(sub_xy)

# 3 Multiply array with integer
mult_x = x * 3
print("\n3. x * 3:")
print(mult_x)

# 4 Square of each element
square_x = x ** 2
print("\n4. Square of x:")
print(square_x)

# 5 Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print(f"\n5. Dot products:")
print(f"v · w = {dot_vw}")
print(f"x · v = {dot_xv}")
print(f"x · y = \n{dot_xy}")

# 6 Concatenation
concat_row = np.concatenate((x, y), axis=0)
concat_col_vw = np.column_stack((v, w))
print("\n6. Concatenation:")
print(f"x and y along rows:\n{concat_row}")
print(f"v and w along columns:\n{concat_col_vw}")

# 7 Concatenate x and v (with error explanation)
try:
    concat_xv = np.concatenate((x, v))
    print(f"x and v concatenated:\n{concat_xv}")
except ValueError as e:
    print(f"\n7. Error concatenating x and v: {e}")
    print("Explanation: Arrays have different dimensions - x is 2D (2,2) and v is 1D (2,).")
    print("They must have the same number of dimensions for concatenation.")

Original arrays:
x = 
[[1 2]
 [3 5]]
y = 
[[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

1. x + y:
[[ 6  8]
 [10 13]]

2. x - y:
[[-4 -4]
 [-4 -3]]

3. x * 3:
[[ 3  6]
 [ 9 15]]

4. Square of x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
v · w = 219
x · v = [29 77]
x · y = 
[[19 22]
 [50 58]]

6. Concatenation:
x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along columns:
[[ 9 11]
 [10 12]]

7. Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Arrays have different dimensions - x is 2D (2,2) and v is 1D (2,).
They must have the same number of dimensions for concatenation.


In [5]:
#Matrix Operations:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
I = np.eye(2)  # Identity matrix

print("Given matrices:")
print(f"A = \n{A}")
print(f"B = \n{B}")

# 1 Prove A · A⁻¹ = I
A_inv = np.linalg.inv(A)
proof_1 = np.dot(A, A_inv)
print("\n1. Proof A · A⁻¹ = I:")
print(f"A · A⁻¹ = \n{proof_1}")
print(f"Identity matrix: \n{I}")
print(f"Are they equal? {np.allclose(proof_1, I)}")

# 2 Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. Proof AB ≠ BA:")
print(f"AB = \n{AB}")
print(f"BA = \n{BA}")
print(f"Are they different? {not np.array_equal(AB, BA)}")

# 3 Prove (AB)ᵀ = BᵀAᵀ
AB_transpose = AB.T
B_trans_A_trans = np.dot(B.T, A.T)
print("\n3. Proof (AB)ᵀ = BᵀAᵀ:")
print(f"(AB)ᵀ = \n{AB_transpose}")
print(f"BᵀAᵀ = \n{B_trans_A_trans}")
print(f"Are they equal? {np.array_equal(AB_transpose, B_trans_A_trans)}")

# Solving system of linear equations
print("\n4. Solving System of Linear Equations:")
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form: AX = B
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

print(f"Coefficient matrix A:\n{A_eq}")
print(f"Constants vector B: {B_eq}")

# Using inverse method: X = A⁻¹B
try:
    A_inv_eq = np.linalg.inv(A_eq)
    X_solution = np.dot(A_inv_eq, B_eq)
    print(f"\nSolution using inverse method (X = A⁻¹B):")
    print(f"x = {X_solution[0]:.2f}, y = {X_solution[1]:.2f}, z = {X_solution[2]:.2f}")

    # Verify solution
    verification = np.dot(A_eq, X_solution)
    print(f"Verification (A · X): {verification}")
    print(f"Matches B? {np.allclose(verification, B_eq)}")

except np.linalg.LinAlgError as e:
    print(f"Error: {e}")

# Using np.linalg.solve (more numerically stable)
print(f"\nSolution using np.linalg.solve:")
X_solve = np.linalg.solve(A_eq, B_eq)
print(f"x = {X_solve[0]:.2f}, y = {X_solve[1]:.2f}, z = {X_solve[2]:.2f}")

Given matrices:
A = 
[[3 4]
 [7 8]]
B = 
[[5 3]
 [2 1]]

1. Proof A · A⁻¹ = I:
A · A⁻¹ = 
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix: 
[[1. 0.]
 [0. 1.]]
Are they equal? True

2. Proof AB ≠ BA:
AB = 
[[23 13]
 [51 29]]
BA = 
[[36 44]
 [13 16]]
Are they different? True

3. Proof (AB)ᵀ = BᵀAᵀ:
(AB)ᵀ = 
[[23 51]
 [13 29]]
BᵀAᵀ = 
[[23 51]
 [13 29]]
Are they equal? True

4. Solving System of Linear Equations:
Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants vector B: [-1 -3  9]

Solution using inverse method (X = A⁻¹B):
x = 2.00, y = 1.00, z = -2.00
Verification (A · X): [-1. -3.  9.]
Matches B? True

Solution using np.linalg.solve:
x = 2.00, y = 1.00, z = -2.00
